name: Build Windows Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Qt 5.15.2
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Download OBS Studio source
        run: |
          git clone --depth 1 --branch 28.1.3 https://github.com/obsproject/obs-studio.git obs-studio

      - name: Configure CMake
        working-directory: obs-studio
        run: cmake -G "Visual Studio 17 2022" -A x64 ..

      - name: Build Plugin
        working-directory: obs-studio
        run: cmake --build . --config Release --target obs-live-indicator

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: obs-live-indicator-windows
          path: obs-studio/build/obs-plugins/64bit/obs-live-indicator.dll
